services:
  litellm-db:
    image: postgres:16-alpine
    container_name: litellm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=litellm_db
      - POSTGRES_USER=litellm_admin
      - POSTGRES_PASSWORD=litellm_pass
    volumes:
      - litellm_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm_admin -d litellm_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"
    depends_on:
      litellm-db:
        condition: service_healthy
    volumes:
      - ./models_config:/app/config
    environment:
      - DATABASE_URL=postgresql://litellm_admin:litellm_pass@litellm-db:5432/litellm_db
      - LITELLM_MASTER_KEY=sk-DAzu.0429*
    restart: always
    command: [ "--config", "/app/config/litellm_config.yaml", "--port", "4000" ]

volumes:
  litellm_db_data: